/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code.challenges;

public class ArrayShift {
    public int[] insertShiftArray(int[] arr, int val) {
        int[] newArr = new int[arr.length + 1];
        int mid = arr.length / 2;
        if (arr.length % 2 == 1){
            mid += 1;
        }
        for (int i = 0; i < arr.length; i++){
            if (i == mid){
                newArr[i] = val;
                newArr[i + 1] = arr[i];
            } else if (i < mid) {
                newArr[i] = arr[i];
            } else {
                newArr[i + 1] = arr[i];
            }
        }
        return newArr;
    }
}
